language: php

dist: trusty

sudo: false

branches:
  only:
    - master
    - develop
    - releases/1.0.3

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  matrix:
    - DB=mysql DATABASE_URL='mysql://root@127.0.0.1/test_cakevue_spa?init[]=SET sql_mode = "STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"' DB_HOST='127.0.0.1' DB_USERNAME='root' DB_PASSWORD='' DB_NAME='test_cakevue_spa'

services:
  - mysql

matrix:
  fast_finish: true

  global:
    - DEFAULT=1

  include:
    - php: 7.2
      env: PHPCS=1 DEFAULT=0

    - php: 7.2
      env: PHPSTAN=1 DEFAULT=0

    - php: 7.2
      env: CODECOVERAGE=1 DEFAULT=0

before_script:
  - if [ $DB = 'mysql' ]; then mysql -u root -e 'CREATE DATABASE IF NOT EXISTS test_cakevue_spa;'; fi
  - if [[ $PHPCS = 1 ]]; then composer require cakephp/cakephp-codesniffer:^3.0; fi
  - if [[ $DEFAULT = 1 ]]; then composer install --no-interaction; fi
  - if [[ $DEFAULT = 1 ]]; then composer test-setup; fi
  - if [[ $DEFAULT = 1 ]]; then composer run-script post-install-cmd --no-interaction; fi
  - if [[ $DEFAULT = 1 ]]; then bin/cake migrations migrate; fi

  - if [[ $CODECOVERAGE = 1 ]]; then composer install --no-interaction; fi
  - if [[ $CODECOVERAGE = 1 ]]; then composer test-setup; fi

script:
  - if [[ $DEFAULT = 1 ]]; then composer test; fi

  - if [[ $PHPCS = 1 ]]; then vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests ./webroot; fi

  - if [[ $PHPSTAN = 1 ]]; then composer phpstan-setup && composer phpstan; fi

  - if [[ $CODECOVERAGE == 1 ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=clover.xml; fi

after_success:
  - if [[ $CODECOVERAGE == 1 ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false
