language: php

branches:
    only:
        - master
        - upgrade-app-to-cake4

php:
    - 7.2
    # - 7.3

services:
    - mysql

env:
    matrix:
        - DB=mysql DATABASE_TEST_URL='mysql://root@127.0.0.1/test_cakevue_spa'
    global:
        - DEFAULT=1

matrix:
    fast_finish: true

    # global:
    #     - DEFAULT=1
        # - PHPCS=0
        # - PHPSTAN=0
        # - CODECOVERAGE=0

    # include:
    #     - php: 7.2
    #         env: PHPCS=1 DEFAULT=0

    #     - php: 7.2
    #         env: PHPSTAN=1 DEFAULT=0

    #     - php: 7.2
    #         env: CODECOVERAGE=1 DEFAULT=0 DB=mysql DATABASE_TEST_URL='mysql://root@127.0.0.1/test_cakevue_spa'

# before_install:
#     - phpenv config-rm xdebug.ini

# before_script:
#     - if [[ $DB == 'mysql' ]]; then mysql -e 'CREATE DATABASE test_cakevue_spa;'; fi

install:
    - composer install --no-interaction

script:
    - if [[ $DEFAULT = 1 ]]; then composer test; fi

    # - if [[ $PHPCS = 1 ]]; then composer cs-check; fi

    # - if [[ $PHPSTAN = 1 ]]; then composer analyse; fi

    # - if [[ $CODECOVERAGE == 1 ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=clover.xml; fi

# after_success:
#     - if [[ $CODECOVERAGE == 1 ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
    email: false

cache:
    directories:
        - $HOME/.composer/cache
